### ISSUE TITLE
Support loading token from a file.

### ISSUE THREAD

**Issue by tomprince** [codecov/codecov-python#25] opened 2015-05-16 16:09 UTC
Some CI systems ([buildbot](https://buildbot.net/) for example) default to showing the environment and command-line of all commands run. Thus, it would be useful if there was an option to pass a file-name with the token in it, rather than an argument or environment variable.

**Comment by stevepeak** [comment] 2015-05-16 16:29
@tomprince thanks for sharing this: I'll add buildbot integration directly into the uploader soon. Thanks!

**Comment by adiroiban** [comment] 2015-07-19 15:38
Any progress on this? @hawkowl has start working at sending reports from the Twisted project https://codecov.io/github/twisted/twisted ... but it would be nice to have a buildbot step for codecov so that  the token is kept private :)

... but this is not like top secret

**Comment by stevepeak** [comment] 2015-07-19 16:25
@adiroiban the build bot integration is pending. Today I've been working with @hawkowl on getting [Twisted up on Codecov](https://codecov.io/gh/twisted/twisted), its looking good.

@sa2ajj how can I help to continue this integration?

**Comment by sa2ajj** [comment] 2015-07-23 16:49
@stevepeak sorry for the lack of activity: new job takes a lot of my time.

I've been looking at the code and it's a bit difficult to read.  I hope to get something during this weekend.

**Comment by stevepeak** [comment] 2015-08-09 14:48
@sa2ajj this Python uploader (via `wip/1.3.0` branch) can collect all coverage files and can be used as the "primary" uploader for BuildBot. I would like to get this conversation started again and get Codecov integrated: https://github.com/buildbot/buildbot/pull/1671

Cheers!

**Comment by sa2ajj** [comment] 2015-08-10 15:56
The problem I see is exactly the fact that the code tries to collect _all_ files.

In addition, it's not really clear what is the format of the data that needs to be submitted (I gave it next tries and stopped).

**Comment by stevepeak** [comment] 2015-08-10 16:09
> The problem I see is exactly the fact that the code tries to collect all files.

I understand your concerns. I assure you that this happens for a reason. I've discovered over a dozen different report file name. Not additional work is needed to parse them because our server side does. This ability makes Codecov very lean and quick to integrate.

> clear what is the format of the data that needs to be submitted

Codecov accepts **everything** I've seen as far as coverage reports go. I have not seen a new type in months, but if there is a new format I add a parser (server side) in 10 minutes.

I hope this answers your questions and furthermore understand why Codecov behaves like this. Integration with BuildBot can be very swift once we understand what happens here. Thank you!

**Comment by sa2ajj** [comment] 2015-08-11 04:45
[nit] it's Buildbot :)

**Comment by sa2ajj** [comment] 2015-08-11 04:52
Right.

What I'd like to implement is a [build step](http://docs.buildbot.net/current/manual/cfg-buildsteps.html).  There are two options:

* build slave side, which is wrong as all communications with external services [so far] are implemented as a master side activity
* master side, which is difficult since you expect to be able to _walk_ the directories to find all reports that you support; however this is what I am looking at

So what I have in mind is to give an option to the Buildbot administrator to list the files that need to be submitted (since walking build slave directories from the master is a bit too sophisticated).  And the code I'm looking at at `codecov-python` is not exactly easy to read (since it supports everything by walking the tree).

**Comment by stevepeak** [comment] 2015-08-11 14:39
Since the issue is walking through all directories why don't I add an argument to disable this. When used in conjunction with targeting specific files for uploading. Lets take this example:

```sh
codecov -f path/to/coverage.xml -f another/coverage/lcov.info -X toc
```
> - `-X toc` will disable Codecov's walking through directories. (**not** programmed atm, but can add)
> - `-f :path` can tell Codecov to directly target specific coverage reports for uploading.

Thoughts?

**Comment by adiroiban** [comment] 2015-08-11 14:45
Just some feedback... in case it help.

Rather than using a single builder / single step to generate all coverage reports, I have multiple builders.

Each builder will generate a single report. Some builders will generate the JS unit reports on Chrome, others on IE ... other Python for Windows or Python 2.7 for Linux.

The reports are later aggregated using a 3rd party process.. but I see that codecov knows how to aggregate them... which is nice.

I think that having a step configured with a list of coverage files is fine.

Thanks for working on this.

**Comment by stevepeak** [comment] 2015-08-11 14:47
@adiroiban thank you :) 

fwiw in addition to what @adiroiban is saying: you can call `codecov` multiple times with different files. Our backend automatically unifies the reports, no extra setup necessary.

**Comment by sa2ajj** [comment] 2015-08-12 20:27
@stevepeak if you'd implement those options in `codecov-python` that'd help a lot.

**Comment by stevepeak** [comment] 2015-08-12 21:04
They are programmed and ready to be released within a week :)

**Closed** 2015-08-15 19:40 UTC

**Comment by stevepeak** [comment] 2015-08-21 18:23
Hey @sa2ajj the new package is live. Let me know how I can help out more with this integration. :+1:
