### ISSUE TITLE
HTTP 400 while uploading to s3 with python codecov

### ISSUE THREAD

**Issue by Borda** [codecov/codecov-python#251] opened 2020-05-17 21:57 UTC
We have a public repo which is built on Drone.io and everything was fine until yesterday...
According to the [Codecov commit history](https://codecov.io/gh/PyTorchLightning/pytorch-lightning/branch/master/commits?page=1) the reports start failing about 24h ago without any change in Codecov config or CI configuration...
It seems to be strictly failing on uploading to S3, see the error:
```
+ codecov --token $CODECOV_TOKEN
--
1765 | find: unknown predicate `-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**''
1766 |  
1767 | _____          _
1768 | / ____\|        \| \|
1769 | \| \|     ___   __\| \| ___  ___ _____   __
1770 | \| \|    / _ \ / _  \|/ _ \/ __/ _ \ \ / /
1771 | \| \|___\| (_) \| (_\| \|  __/ (_\| (_) \ V /
1772 | \_____\___/ \____\|\___\|\___\___/ \_/
1773 | v2.0.22
1774 |  
1775 | ==> Detecting CI provider
1776 | -> Got branch from git/hg
1777 | -> Got sha from git/hg
1778 | ==> Preparing upload
1779 | ==> Processing gcov (disable by -X gcov)
1780 | Executing gcov (['find', '/drone/src', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+'])
1781 | Error running `['find', '/drone/src', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']`: Command '['find', '/drone/src', "-not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**'", '-type', 'f', '-name', '*.gcno', '', '-exec', 'gcov', '-pb', '', '{}', '+']' returned non-zero exit status 1.
1782 | ==> Collecting reports
1783 | Generating coverage xml reports for Python
1784 | + /drone/src/coverage.xml bytes=175982
1785 | ==> Uploading
1786 | .url https://codecov.io
1787 | .query commit=07b61c36d7ed5d6a731cd06096f967b85d1a2b92&branch=master&token=<secret>&yaml=.codecov.yml&package=py2.0.22
1788 | Pinging Codecov...
1789 | Uploading to S3...
1790 | Error: 400 Client Error: Bad Request for url: https://storage.googleapis.com/codecov/v4/raw/2020-05-17/58A692D2985A264F96A68126BE73B9B0/07b61c36d7ed5d6a731cd06096f967b85d1a2b92/8e03c21c-d0d8-4fc3-91c7-805790ffbff4.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EQX6OZVJGHKK3633AAFGLBUCOOATRACRQRQF6HMSMLYUP6EAD6XSWAAY%2F20200517%2FUS%2Fs3%2Faws4_request&X-Amz-Date=20200517T212109Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=8d778eb999bad1df2ef43dd5d9eef1ae407b032f69162876568618cf8469bbad
1791 |  
1792 | Tip: See all example repositories: https://github.com/codecov?query=example
1793 | Support channels:
1794 | Email:   hello@codecov.io
1795 | IRC:     #codecov
1796 | Gitter:  https://gitter.im/codecov/support
1797 | Twitter: @codecov
```
see: http://35.192.60.23/PyTorchLightning/pytorch-lightning/2962/1/2
the very same issue was also reported on support by others:
https://community.codecov.io/t/http-400-while-uploading-to-s3-with-python-codecov-from-travis/1428

**Comment by enmatt** [comment] 2020-05-17 23:12
Same here. I saw on their status page that they did storage infrastructure maintenance Saturday morning.

**Comment by knary** [comment] 2020-05-18 01:12
Also seeing it: https://ci.appveyor.com/project/knary/labbook/builds/32938815/job/1o7413jw5p3fcfnf

**Comment by knutster** [comment] 2020-05-18 10:09
Same here from a circleci build

**Comment by hootener** [comment] 2020-05-18 11:13
@ThiagoCodecov has submitted a fix in #253 . We'll get that merged today, along with #252

**Comment by Borda** [comment] 2020-05-18 11:38
by the PRs' name it does not look very relevant... so is it fixed now in master?

**Comment by eric-wieser** [comment] 2020-05-18 16:07
This looks merged, but it'll need a release to PyPI to help people using CI.

**Comment by Borda** [comment] 2020-05-18 16:25
it seems that it is working now, so some temporary S3 issue...

**Comment by kmpaul** [comment] 2020-05-22 19:35
It is not working for me.

**Comment by kmpaul** [comment] 2020-05-22 19:55
Ok.  Sorry for the noise.  I verified that I can indeed get `codecov` to work properly if I install from the master branch (instead of the latest release).

**Comment by interDist** [comment] 2020-05-24 23:12
@Borda looks like the issue is resolved. 

I had to update in project dependencies (requirements) the version of `codecov` to 2.1.3.

**Closed** 2020-06-04 04:34 UTC
