### ISSUE TITLE
Version 2.1.3 fails to find gcov files

### ISSUE THREAD

**Issue by pganssle** [codecov/codecov-python#261] opened 2020-05-22 16:25 UTC
Recently codecov stopped uploading my C code coverage on a Python C extension I have written.

In [this job](https://github.com/pganssle/zoneinfo/runs/696921785?check_suite_focus=true), `tox` is using `codecov==2.1.1`, and the upload succeeds.

In [this job](https://github.com/pganssle/zoneinfo/runs/697452420?check_suite_focus=true), `tox` is using `codecov==2.1.3` and I see the following error:

```
==> Detecting CI provider
  -> Got branch from git/hg
  -> Got sha from git/hg
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (gcov -pb  .../zoneinfo/.tox/gcov/coverage/build/temp.linux-x86_64-3.8/lib/zoneinfo_module.gcno)
    Error running `gcov -pb  .../zoneinfo/.tox/gcov/coverage/build/temp.linux-x86_64-3.8/lib/zoneinfo_module.gcno`: 
        [Errno 2] No such file or directory: 'gcov -pb  .../zoneinfo/.tox/gcov/coverage/build/temp.linux-x86_64-3.8/lib/zoneinfo_module.gcno'
Error: 'NoneType' object has no attribute 'replace'
```

(I've modified this slightly to make it a bit easier to read by shortening some paths and breaking up one extra long line).

Unfortunately I don't have time to create a minimal reproducer, but if you clone [the zoneinfo repository](https://github.com/pganssle/zoneinfo) and run `tox -e gcov`, that should generate the coverage files, and I'm using `scripts/upload_codecov.py` to upload the coverage files — it is just a script that finds the XML file output that `gcovr` emits, and passes that to `codecov -f`.

I'm guessing https://github.com/codecov/codecov-python/issues/167 is the culprit.

**Comment by nmoinvaz** [comment] 2020-05-22 16:43
I do notice that it uses three dots `...`

**Comment by pganssle** [comment] 2020-05-22 16:46
@nmoinvaz That's actually part of the "slight modifications" 😅, anywhere you see the three dots, replace it with `/home/runner/work/zoneinfo`.

(I also noticed that my original link was not a "permalink" and changed when I pushed a new fix to the PR, I've now updated it to be a permalink).

**Comment by nmoinvaz** [comment] 2020-05-22 16:51
I think this might be fixed with the latest master branch since it no longer uses `find` command.
https://github.com/codecov/codecov-python/commit/65d596e454d7a24fd0114418d1f13e6e5f66f0ee
I recommend testing some how with master if you can.

**Comment by pganssle** [comment] 2020-05-22 16:56
@nmoinvaz No, I'm pretty sure that's the commit that _broke_ `codecov`. It works fine with the latest version using the `find` command (version 2.1.1 — confirmed by pinning this in my `codecov` tox environment).

**Comment by nmoinvaz** [comment] 2020-05-22 16:58
I see the version numbers on Pypi are different than in git.

**Comment by drazisil** [comment] 2020-05-22 16:59
If that broke it, I'm going to to need to rollback, unless you can somehow test this @nmoinvaz ?

**Comment by nmoinvaz** [comment] 2020-05-22 16:59
Ok I will take a look at it

**Comment by pganssle** [comment] 2020-05-22 16:59
> I see the version numbers on Pypi are different than in git.

See #256

**Comment by nmoinvaz** [comment] 2020-05-22 18:49
I think it might have to do with how you are are calling codecov. If you change it to os.system call, for me it does not have that problem. I think it might not be able to find gcovr, because when I run the command it fails on, it works and the file does exist.

**Comment by nmoinvaz** [comment] 2020-05-22 19:14
I was able to reproduce. I have two commits that should help. Please give them a shot.

**Comment by nmoinvaz** [comment] 2020-05-29 01:36
This should be resolved now.

**Comment by thomasrockhu** [comment] 2020-06-03 19:28
Fixed via https://github.com/codecov/codecov-python/pull/263

**Closed by thomasrockhu** 2020-06-03 19:28 UTC
Labels: bug, help wanted
