### ISSUE TITLE
Failed 'Uploading to S3' step

### ISSUE THREAD

**Issue by lycantropos** [codecov/codecov-python#212] opened 2019-10-03 15:04 UTC
From some moment I've started to get
```bash
==> Uploading
    .url https://codecov.io
    .query commit=6a1f30c0781f4403ce6316808032ab88d1c20e14&branch=HEAD&token=<secret>&package=py2.0.15
    Pinging Codecov...
    Uploading to S3...
Error: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

For example [this **Travis CI** job](https://travis-ci.org/lycantropos/paradigm/jobs/593075299) (and the whole build as well) and [this **Azure DevOps** build](https://dev.azure.com/lycantropos/paradigm/_build/results?buildId=629&view=logs&j=3075192c-09d7-5d97-1701-9d7cb9f4b8fc) (*Upload coverage* step).

**Comment by peter-featherstone** [comment] 2019-10-03 15:44
Confirmed. We have started getting this across all our repos in the past 8 hours.

**Comment by ibrahimroshdy** [comment] 2019-12-25 10:52
Any updates on this? Facing the same issue.

**Comment by desilinguist** [comment] 2020-03-13 16:41
I am now seeing the same thing on my repo starting just now.

**Comment by desilinguist** [comment] 2020-03-13 16:44
The error I am saying is more about a timeout:

```
HTTPSConnectionPool(host='codecov.io', port=443): Max retries exceeded with url: ... (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdb7ec4d6a0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by nmoinvaz** [comment] 2020-03-14 04:58
I started having better success after I added gzip support for S3. You can try using my branch or PR.

**Comment by thomasrockhu** [comment] 2020-11-29 19:33
I'm going to close this out due to age, but if you are still experiencing issues, please open a ticket in our [community boards](https://community.codecov.io)

**Closed by thomasrockhu** 2020-11-29 19:33 UTC
